<#assign tableNameCapFirst = "${tableName?cap_first}">
<#if pkgName??>
package ${pkgName}.domain;
</#if>

import lombok.Data;
<#list fieldInfos as fieldInfo>
import ${fieldInfo.dbFieldType.pkg};
</#list>

/**
 * Generated by ${generatedBy} on ${generatedTime?string["yyyy/MM/dd"]}.
 */
@Data
public class ${tableNameCapFirst}{

<#list fieldInfos as fieldInfo>
    private ${fieldInfo.dbFieldType.type} ${fieldInfo.fieldName};

</#list>

}