<#assign tableNameCapFirst = "${tableName?cap_first}">
<#if pkgName??>
package ${pkgName}.dao;
</#if>

import ${pkgName}.domain.${tableNameCapFirst};
import java.util.List;

/**
 * Generated by ${generatedBy} on ${generatedTime?string["yyyy/MM/dd"]}.
 */
public interface ${tableNameCapFirst}Mapper {
    List<${tableNameCapFirst}> queryAll();
}
