<#assign tableNameCapFirst = "${tableName?cap_first}">
<#if pkgName??>
package ${pkgName}.controller;
</#if>

import ${pkgName}.domain.${tableNameCapFirst};
import ${pkgName}.service.${tableNameCapFirst}Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.HttpStatus;
import java.util.List;

/**
 * Generated by ${generatedBy} on ${generatedTime?string["yyyy/MM/dd"]}.
 */
@RestController
@RequestMapping("/api")
public class ${tableNameCapFirst}Controller{

    @Autowired
    private ${tableNameCapFirst}Service ${tableName}Service;

    @RequestMapping(value = "/queryAll",method = RequestMethod.GET)
    public ResponseEntity<List<${tableNameCapFirst}>> queryAll(){
        return new ResponseEntity<>(${tableName}Service.queryAll(),HttpStatus.OK);
    }
}